[package]
name = "txt_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", rev = "refs/tags/text-editor" , features = ["debug"] }
tokio = { version = "1.46.1" , features = ["fs"] }
rfd = "0.15.3"